name: Build and Publish Container Image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@main

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@e19285db868b7ebd44ff6b457ba624dec20f5734  # master as of 2022-04-25
      with:
        # Proactively build on mybinder.org for faster startup.
        MYBINDERORG_TAG: ${{ github.event.ref }}
        # Also push built image to DockerHub for use by our JupyterHub deployments.
        DOCKER_USERNAME: nsls2damaservice
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        IMAGE_NAME: "nsls2/um2022"
